idf_component_register(
    SRCS
        "ota_service.c"
    INCLUDE_DIRS
        "include"
    REQUIRES
        app_update
        bootloader_support
        esp_app_format
        esp_event
        esp_http_client
        esp_timer
        freertos
        ha_discovery
        ha_mqtt
        network
)
